version: "3.1"

services:
  easyrtc-server:
    image: easyrtc-server:${EASYRTC_VERSION:-latest}
    container_name: easyrtc-server
    build:
      context: .
      args:
        EASYRTC_BRANCH: "master"
    command: server_ssl
    volumes:
      - ./certs:/usr/src/app/certs:ro
      - ./static:/static:ro
    networks:
      - frontend
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true

networks:
  frontend:
  backend:
